### ISSUE TITLE
Shape Mismatch Error in 4track Model (epoch=18-step=20000.ckpt)

### ISSUE THREAD

**Issue by Luoyunfan-Jason** [bowang-lab/Orthrus#5]
I encountered a RuntimeError while using the 4-track model (orthrus_base_4_track) example. Specifically, when my input torch_one_hot has a shape of (1, 4, 495), I get the following error:

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (495x4 and 6x256)`
Upon inspecting the model, I noticed that the embedding layer is defined as:

`(embedding): Linear(in_features=6, out_features=256, bias=True)`
Since in_features is set to 6, the error occurs when torch_one_hot has 4 features. However, when I modify the input to have a shape of (1, 6, 495), the code runs successfully and produces an output of `torch.Size([1, 256])`.

Question:
Is there a version of the model that works with a 4-track input, or is it necessary to use zero padding to convert the input to 6 features?
Thanks

**Comment by phil-fradkin** [comment]
Hi Yufan our cluster is down today but it looks like I might have uploaded either the wrong data config or the wrong config and ckpt file to huggingface (it looks like it's the 6 track version). 

I should be able to verify and update huggingface tomorrow, sorry about that!

**Comment by phil-fradkin** [comment]
Hi Yufan it should be working now. Please let me know if it doesn't work for you!

**Comment by Luoyunfan-Jason** [comment]
Hi Phil,
Thank you so much for your prompt response and help in resolving the issue, and I’m grateful for the support you provided. The updated version is working smoothly now!
